package POJO;
// Generated 23.02.2019. 00:17:59 by Hibernate Tools 4.3.1



/**
 * Aviokompanija generated by hbm2java
 */
public class Aviokompanija  implements java.io.Serializable {


     private Integer id;
     private Osiguranje osiguranje;
     private Zaposlenik zaposlenik;
     private String naziv;
     private String let;
     private String avion;
     private String oib;
     private String iban;

    public Aviokompanija() {
    }

    public Aviokompanija(Osiguranje osiguranje, Zaposlenik zaposlenik, String naziv, String let, String avion, String oib, String iban) {
       this.osiguranje = osiguranje;
       this.zaposlenik = zaposlenik;
       this.naziv = naziv;
       this.let = let;
       this.avion = avion;
       this.oib = oib;
       this.iban = iban;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Osiguranje getOsiguranje() {
        return this.osiguranje;
    }
    
    public void setOsiguranje(Osiguranje osiguranje) {
        this.osiguranje = osiguranje;
    }
    public Zaposlenik getZaposlenik() {
        return this.zaposlenik;
    }
    
    public void setZaposlenik(Zaposlenik zaposlenik) {
        this.zaposlenik = zaposlenik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getLet() {
        return this.let;
    }
    
    public void setLet(String let) {
        this.let = let;
    }
    public String getAvion() {
        return this.avion;
    }
    
    public void setAvion(String avion) {
        this.avion = avion;
    }
    public String getOib() {
        return this.oib;
    }
    
    public void setOib(String oib) {
        this.oib = oib;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }




}


