package POJO;
// Generated 23.02.2019. 00:17:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zaposlenik generated by hbm2java
 */
public class Zaposlenik  implements java.io.Serializable {


     private Integer id;
     private int avioKompanija;
     private String ime;
     private String prezime;
     private String email;
     private int brojMobitela;
     private Integer brojUgovora;
     private String oib;
     private Set aviokompanijas = new HashSet(0);

    public Zaposlenik() {
    }

	
    public Zaposlenik(int avioKompanija, String ime, String prezime, String email, int brojMobitela) {
        this.avioKompanija = avioKompanija;
        this.ime = ime;
        this.prezime = prezime;
        this.email = email;
        this.brojMobitela = brojMobitela;
    }
    public Zaposlenik(int avioKompanija, String ime, String prezime, String email, int brojMobitela, Integer brojUgovora, String oib, Set aviokompanijas) {
       this.avioKompanija = avioKompanija;
       this.ime = ime;
       this.prezime = prezime;
       this.email = email;
       this.brojMobitela = brojMobitela;
       this.brojUgovora = brojUgovora;
       this.oib = oib;
       this.aviokompanijas = aviokompanijas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAvioKompanija() {
        return this.avioKompanija;
    }
    
    public void setAvioKompanija(int avioKompanija) {
        this.avioKompanija = avioKompanija;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getBrojMobitela() {
        return this.brojMobitela;
    }
    
    public void setBrojMobitela(int brojMobitela) {
        this.brojMobitela = brojMobitela;
    }
    public Integer getBrojUgovora() {
        return this.brojUgovora;
    }
    
    public void setBrojUgovora(Integer brojUgovora) {
        this.brojUgovora = brojUgovora;
    }
    public String getOib() {
        return this.oib;
    }
    
    public void setOib(String oib) {
        this.oib = oib;
    }
    public Set getAviokompanijas() {
        return this.aviokompanijas;
    }
    
    public void setAviokompanijas(Set aviokompanijas) {
        this.aviokompanijas = aviokompanijas;
    }




}


